package com.riteny.util.exception.core.exception


object CommonExceptionStatus {
    const val STATUS_ERROR: Int = 0
}
